name: C++ Build

on:
  workflow_dispatch:
      # Enable manual run
  push:
      tags:
          - "v*" # Push events to matching v*, i.e. v4.2.0

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: actions-setup-cmake
        uses: jwlawson/actions-setup-cmake@v1.14.1
        with:
          cmake-version: '3.22.x'

      - name: Build C++ program
        run: |
          cd src
          mkdir -p build
          cd build
          cmake ..
          cmake --build .  # Use CMake to build the project
          cd ../..

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ggmlclip-${{ matrix.os }}
          path: src/build/ggmlclip
      # Create a Github release
        uses: ncipollo/release-action@v1
        with:
            artifacts: "src/build/ggmlclip"
            token: ${{ secrets.GITHUB_TOKEN }}